#  transpose of a matrix
# def transpose_matrix(matrix):
#     transposed_matrix=[[matrix[j][i]
#     for j in range (len(matrix))]
#     for i in range(len(matrix[0]))]
#     return transposed_matrix
# matrix=[
#     [1,2,3],
#     [4,5,6],
#     [7,8,9],
# ]
# transposed=transpose_matrix(matrix)
# print("original matrix:")
# for row in matrix:
#     print (row)
# print("\ntransposed matrix")
# for raw in transposed:
#     print(row)    
                        
# Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.

# line=input("enter a line of text:")
# print(line.upper())

# animal=input("enter animal name:")
# print(animal.upper())
            